### ISSUE TITLE
Error with lcm show

### ISSUE THREAD

**Issue by timeapen** [rtcTo/rtc2git#101]
Hi All,

I am trying to migrate an RTC repository and get the following error:

Unknown subcommand "show"
'lscm --show-alias n --show-uuid y show attributes -r https:/ rbcis-sf.fg.rbc.com/ccm -w RBCONE_SAMPLE_STR_MASTER' returned non-zero exit status.

I am using the RTC ScmTools 5.0.1 as indicated in the readme.

As a note, the RTC server is 4.0.1.

**Comment by AdamBrousseau** [comment]
"show" was not available in RTC 4.0.1
https://jazz.net/help-dev/clm/topic/com.ibm.team.scm.doc/topics/show.html

The readme says the tool was tested using 5.0.1
https://github.com/rtcTo/rtc2git#prerequirements

You could try upgrading the server.
You could also try newer client tools but I doubt they will work with an older server version.

Another thought I had was to swap out the show command for something available in 4.0.1 that can get you the same info if possible?

**Comment by timeapen** [comment]
Thanks!

- I don't have control over the server so upgrading it is not possible

- Actually I am using the 5.0.1 ScmTools against a 4.0.1 RTC Server - so it seems the server doesn't understand the syntax of the commands when they are executed?

- Option 3 is possible, I am not familiar with RTC thought.  Do you think the 'workspace propertylist' command would gather the same info?  http://www.ibm.com/support/knowledgecenter/SSYMRC_4.0.1/com.ibm.team.scm.doc/topics/workspace_propertylist_ex.html

**Comment by reinhapa** [comment]
You could also look at our other project [rtctocli](https://github.com/rtcTo/rtc2gitcli) that is a RTC client extension. That we actually used to migrate our code base and has the possibility to merge multiple RTC components into one GIT repository.

**Comment by timeapen** [comment]
Thanks.  I gave the rtctocli a shot.  When I execute the scm load command to load the target workspace, I get the following error:

java.lang.IllegalStateException: Found two dtoEvolution elements with the same c
omponentVersion value in bundle com.ibm.team.scm.common.

**Comment by timeapen** [comment]
Closed issue by mistake

**Comment by WtfJoke** [comment]
> Actually I am using the 5.0.1 ScmTools against a 4.0.1 RTC Server - so it seems the server doesn't understand the syntax of the commands when they are executed?

Yeah, this is most likely the case if you get these errors. Also Adam pointed out, that this command doesnt exist in 4.0.1 (which seems to be the case, comparing the link he provided from 6.0.1 and the link you provided from 4.0.1). 

> Option 3 is possible, I am not familiar with RTC thought. Do you think the 'workspace propertylist' command would gather the same info? http://www.ibm.com/support/knowledgecenter/SSYMRC_4.0.1/com.ibm.team.scm.doc/topics/workspace_propertylist_ex.html

Maybe, just try executing following command and tell us the result:
`lscm --show-alias n --show-uuid y  workspace propertylist STREAMNAME  -r REPO`

In worst case you can get around this command by editing some code-lines. We need this command only for getting the uuid of the provided stream automatically.
