### ISSUE TITLE
'StreamtoMigrate' can't handle a Stream name with spaces

### ISSUE THREAD

**Issue by hachillesIBM** [rtcTo/rtc2git#104]
tried putting quotes & escape characters, but got errors from the script..

Workaround:  use the stream's UUID instead of the name if it has spaces..

**Comment by AdamBrousseau** [comment]
You could also duplicate the stream and call it something without spaces

**Comment by ohumbel** [comment]
I simply renamed the stream before the migration.
For example from
`Cross Main Stream`
into
`CrossMainStream`

**Comment by ohumbel** [comment]
Or into `Cross_Main_Stream`

**Comment by ohumbel** [comment]
See also the discussion in issue #51

**Comment by idgserpro** [comment]
@ohumbel  I find a good rtc feature allow name of stream with spaces. It would not be better to have a configuration:

```RenameGitBranch```

?

@WtfJoke It is possible?

**Comment by WtfJoke** [comment]
Since there is such an easy workaround, ohumbel already tried to solve it without success and because I dont have any access to an rtc server for testing, I wont fix this.

I made readme enhancements to make it clear for future users.

Thanks for reporting :)
