### ISSUE TITLE
FileNotFoundError in gitFunctions.py

### ISSUE THREAD

**Issue by hachillesIBM** [rtcTo/rtc2git#106]
I was running into a problem where the routine "handle_capitalization_filename_changes" was trying to change to a directory that it couldn't find.. but was actually there.  (error traceback below).
### The issue was that the code was already running in the sandbox directory when  os.chdir command tried to change to <sandbox/newfilerelativepath>.
# 

I changed the following code in gitFunctions.py and it seems to be running (lots of changes to apply so I don't know if it all works yet):
 Around line 109.  
       from:
          directoryofnewfile=os.path.dirname(os.path.join(sandbox,newfilerelativepath))
        to:
          directoryofnewfile=os.path.dirname(newfilerelativepath)

Around line 112 
        from: 
          os.chdir(directoryofnewfile)
        to: 
           if os.path.exists(directoryofnewfile):
              os.chdir(directoryofnewfile)

```
  The second change is needed for files that occur at the top level of the repo..
```
# 

   Traceback (most recent call last):
      File "./migration.py", line 169, in <module>
        migrate()
      File "./migration.py", line 78, in migrate
        rtc.acceptchangesintoworkspace(rtc.getchangeentriestoaccept(changeentries, history))
      File "<user dir>/rtcFunctions.py", line 223, in acceptchangesintoworkspace
        Commiter.addandcommit(changeEntry)
      File "<user dir> /gitFunctions.py", line 94, in addandcommit
        Commiter.handle_captitalization_filename_changes()
      File "<user dir>/gitFunctions.py", line 116, in handle_captitalization_filename_changes
        os.chdir(directoryofnewfile)
    FileNotFoundError: [Errno 2] No such file or directory: '<sandbox>/FtpRequestPortlet'

**Comment by WtfJoke** [comment]
Do you have by any chance a testcase for this, so I can reproduce this behaviour in order to fix it?
