### ISSUE TITLE
Current load method does not handle sync conflicts

### ISSUE THREAD

**Issue by jbaskeen** [rtcTo/rtc2git#108]
During a migration workspace conflicts can arise through accepting certain change sets which require a reload of the repository workspace to prevent "sync errors". This sometimes happens when using RTC in Eclipse, for example. The Pending Changes view will require you to reload the repository workspace to resolve these kinds of conflicts.

The current `WorkspaceHandler.load()` method in `rtcFunctions.py` does not account for this since the scenario requires that the workspace sandbox directory be cleaned with a reload following that. This means removing the `.jazzShed` & `.jazz5` directories, which is essentially what Eclipse does in these scenarios I believe. A new method `reload()` can be added and triggered within `ImportHandler.acceptchangesintoworkspace()` when changes cannot be accepted.

I have a fix locally and will work on pushing it forward here ASAP after running more tests.

**Comment by WtfJoke** [comment]
I am aware of sync errors in eclipse. Didnt know that you can just delete these two folders to resync it.

Can you provide the fix and maybe a testcase?
