### ISSUE TITLE
Renamed file not renamed during migration

### ISSUE THREAD

**Issue by ljhaywar** [rtcTo/rtc2git#31]
I'm going through and verifying the post-migration content matches what is in RTC.  I have a file that I'm assuming was renamed at some point during its history as the file begins with a lowercase in the migrated Git repo but does not in the RTC repo.  The content of the files is identical.  I'm wondering if the Git commands used in the script did not take into account the file rename?  Does that ring any bells with you?

**Comment by ljhaywar** [comment]
I think this could be a git setting issue.  core.ignorecase was set to true.  I've set it to false and am going to run a test.  Details on core.ignorecase: http://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git

**Comment by WtfJoke** [comment]
> Does that ring any bells with you?

Well I experienced the same. I thought its because windows have case insensitive filenames. So I thought its more of a windows problem... 

Let me know if the git config change helps.

I have planned to run the migration on a linux system anyways... I also got a bunch of cr/lf warnings.

**Comment by ljhaywar** [comment]
Changing the git config did not fix the problem for me.  I still ended up with file names having the wrong capitalization.  I'll keep investigating.

**Comment by ljhaywar** [comment]
Update:  Despite my attempt at setting core.ignorecase to false, when I just ran "git config core.ignorecase" in my branch, it returned true.  I'm going to investigate why the setting is set to true and see if I can run another test with it actually set to false.

**Comment by ljhaywar** [comment]
Update: When I ran "git config --last", I saw both "core.ignorecase=false" and "core.ignorecase=true."  I just ran "git config --replace-all core.ignorecase false" and now I see "core.ignorecase=false" listed twice.  Then I ran "git config core.ignorecase" and now it returns false.  Will try testing now.

**Comment by ljhaywar** [comment]
I restarted the script.  I ran git config core.ignorecase immediately after the branch was created, and it was set to true.  I changed it to false while the script was running, but it should be before any of the file name changes.  If this works, I'll likely add a command to gitFunctions' initialize() to update the setting.

**Comment by WtfJoke** [comment]
> I'll likely add a command to gitFunctions' initialize() to update the setting.

Yeah I think I'll do the same anyways. I was wondering why the git default config is ignorecase true... Its because FAT cant differ those and therefore this seems to be the default. 

Just based how rtc handles and personally I think its correct to set ignorecase to false. I'll update that.

**Comment by ljhaywar** [comment]
Sadly, my test didn't work as I hoped. 

Good:
With core.ignorecase set to false, the files that had the incorrect capitalization in the file name (in previous migration tests) are now correct in my local git repo.  

Bad:
When I pushed that repo to gitlab, the file exists twice in the same directory -- once with the wrong capitalization and once with the right capitalization.  This happened for all 6 of my files that had incorrect capitalization.  

Investigating...

**Comment by ljhaywar** [comment]
I just ran a test with a very small repository workspace that only had one file.

When core.ignorecase is set to false, the file whose name changes capitalization exists twice: once with the old capitalization and once with the new capitalization.

When core.ignorecase is set to true, the file whose name changes capitalization remains with the old capitalization. 

I need to figure out how force Git to rename files.

**Comment by ljhaywar** [comment]
From googling, it looks like the best way to rename files is:
git -mv -f oldFileName newFileName

I see two potential ways to solve the problem, but I'm not sure yet how to implement either of them.  Here is what I'm thinking:

If we run with core.ignorecase = false:
File is renamed from one to One.
git status shows a new untracked file One
At this point, could loop through all files in git status (this is the part I don't currently know how to do--not sure how to pull in data from git status) and do a test 
 - if gitFilename.lowerCase equals fileSystemFilename.lowerCase && gitFilename does not equal fileSystemFilename {
            loop through all files in the same directory
                   delete any other files whose toLowerCase matches gitFilename.toLowercase
}

If we run core.ignorecase = true:
File is renamed from one to One
git status shows nothing
Could loop through all files in the incoming changeset (this is the part I don't currently know how to do) and test if the filename matches what is currently in the file system.  If not, do a git -mv -f oldFilename newFilename.

I think the core.ignorecase = true option will be a bit more efficient.  At this point, I'm not sure how to pull in the data I need.  Any suggestions on how to implement this, direction to go, etc?

**Comment by WtfJoke** [comment]
> If we run with core.ignorecase = false:
> File is renamed from one to One.
> git status shows a new untracked file One
> At this point, could loop through all files in git status (this is the part I don't currently know how to do--not sure how to pull in data from git status) and do a test
> 
>     if gitFilename.lowerCase equals fileSystemFilename.lowerCase && gitFilename does not equal fileSystemFilename { loop through all files in the same directory delete any other files whose toLowerCase matches gitFilename.toLowercase }
> 
> If we run core.ignorecase = true:
> File is renamed from one to One

I think this can work. Maybe its possible to parse the git status output... And then acess those filename.

I think @ohumbel wants to solve #33 similar as far as I am aware of. Im not sure, though if that still the most current solution approach. :smile:  What do you think about that? 



> Could loop through all files in the incoming changeset (this is the part I don't currently know how to do)

There is a changeset extract command. However whenever I tried to extract a changeset I got some crazy jazz-exceptions. Maybe you're lucky and can give it a try.

**Comment by ljhaywar** [comment]
Do you know how to parse git status output from inside the script?  That part is mysterious to me.

**Comment by WtfJoke** [comment]
You might need to read into the topic a bit more. But as far as I know you could use "git status -z" or "git status --porcelain" (see https://git-scm.com/docs/git-status - porcelain contains linebreaks whereas -z does not).


Pass this commands to shell#getoutput and then parse the result. 

I just ran these command and get following output. I think with that its possible to do something. :)

```
E:\rtc2git\tests\resources>git status --porcelain
 D tests/resources/test_rtcFunctions_SampleCompareOutputInUtf8.txt
?? tests/resources/Test_rtcFunctions_SampleCompareOutputInUt8.txt
```

**Comment by ljhaywar** [comment]
Ah - shell.getoutput - the piece I was missing!

**Comment by ljhaywar** [comment]
Thanks!

**Comment by WtfJoke** [comment]
Your welcome :) :+1:

**Comment by ohumbel** [comment]
I have a working parser for the output of git status -z.
It returns a list of file names with status changes (full path inside the repository)
It is not yet pushed to my fork.
It will be part of the solution to #33

**Comment by ljhaywar** [comment]
@ohumbel Do you have a commit we could see?

**Comment by ljhaywar** [comment]
@WtfJoke FYI, in the process of working on this, I realized I could update the script to Resolve with Proposed when a conflict could not be auto-merged.  I was doing this manually myself, but now the script can run continuously without human intervention.  See https://github.com/ljhaywar/rtc2git/commit/40aec2c65f2d0f1e4db2f12c33c50e38e003b9fa & https://github.com/ljhaywar/rtc2git/commit/fde516b5648f1c19178de753a8191576d6fe1d63 for the updates.

**Comment by ohumbel** [comment]
@ljhaywar Regarding output of 'git status -z', I have not yet a push, but a snippet: https://gist.github.com/ohumbel/1271a026a7c016ae4156

I tested on Mac and Windows, and --porcelain added quoting for special characters.
And the layout of moved files is more difficult to parse than the one produced by -z. 
So at the moment -z seems to be true cross platform.

**Comment by ljhaywar** [comment]
Thanks @ohumbel!  I'll take a look.

**Comment by WtfJoke** [comment]
> I was doing this manually myself, but now the script can run continuously without human intervention. See ljhaywar@40aec2c & ljhaywar@fde516b for the updates.

I havent had any internet during the last days, cause I moved. :fearful: But now im back online. :smile: 
I will have a look at it. I will check if this works for my use case as well, cause I have some really bad merge-conflicts (a file which was deleted and modified at the same time). Depending on my tests I will take your changes or not.

Thanks for your inputs :+1:

**Comment by ljhaywar** [comment]
:+1:

**Comment by ljhaywar** [comment]
I've tested and committed a fix for this issue.  
https://github.com/ljhaywar/rtc2git/commit/2a498649e59277b1d35d2039592bb99639ce453a
https://github.com/ljhaywar/rtc2git/commit/da1a9ce506b2c07fed0cc16fef18fb3ecd0eb1db

If you agree @WtfJoke, this issue can be closed.

**Comment by WtfJoke** [comment]
Ah cool, thank you :smile:  Can you open a pull request for them? After that you can close the issue. :+1:

**Comment by ljhaywar** [comment]
Pardon my noobness...  How do I create a pull request?  I haven't been pulling your latest changes to my fork, so I'm not sure if my commits will apply cleanly to your branch.

**Comment by WtfJoke** [comment]
The best way is when you have an untouched branch which follows mine and from there create a separate branch and do the changes. Afterwards push that branch and create pull request. :)

**Comment by ljhaywar** [comment]
I don't see a way to create a branch in your repo.  https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/#creating-a-branch makes it look like I should be able to create a branch.  Perhaps I don't have permission to do so.

If that's the case, do I need to create a new fork?  My current fork doesn't have your latest changes and has additional changes that your project doesn't have.

**Comment by WtfJoke** [comment]
> I don't see a way to create a branch in your repo. https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/#creating-a-branch makes it look like I should be able to create a branch. Perhaps I don't have permission to do so.

I was talking about creating a branch on your fork/project. You do not have permission on my repo


> If that's the case, do I need to create a new fork? My current fork doesn't have your latest changes and has additional changes that your project doesn't have.

No, I think its not necessary that you need to create a new fork. Im not 100% sure about the procedure, but once I did something similar with a project I contributed.

1. First I needed to follow these steps: https://help.github.com/articles/configuring-a-remote-for-a-fork/
2. Afterwards you can checkout the branches of my project - you can find details how you can do that here: https://stackoverflow.com/questions/4410091/github-import-upstream-branch-into-fork
(Creating a branch in your repo, which for example is named joke-develop, original-develop or origin-develop, which is based on my develop branch). 
This newly develop branch you can keep up to date with my changes and leave untouched. 


And whenever you want to contribute something, you can update (if you havent already done that) this develop branch and creating a new branch (featureX) on top of it and out of that newly created branch you can create a pull request.

I hope I didnt explained it too complicated :confounded: :smile:  If something is not clear, just ask :+1:

**Comment by WtfJoke** [comment]
> I will have a look at it. I will check if this works for my use case as well, cause I have some really bad merge-conflicts (a file which was deleted and modified at the same time). Depending on my tests I will take your changes or not.
> 
> Thanks for your inputs :+1:

I had a look on it. Sadly it didnt solve the mentioned bad merge-conflicts. But anyways, I think I am going to implement such a feature (probably use your code :rotating_light: :stuck_out_tongue_winking_eye: from your linked commits) , which can be used on demand if the user wants that.

**Comment by ljhaywar** [comment]
Too bad it didn't resolve your issue. :-1:

**Comment by ohumbel** [comment]
In addition to the already mentioned preparation link:
https://help.github.com/articles/configuring-a-remote-for-a-fork/

I found this one useful to update my fork :
https://help.github.com/articles/syncing-a-fork/

In my case, this lead to some merge conflicts, which I now have to resolve manually..

**Comment by ljhaywar** [comment]
I tried this morning, and I'm struggling.  I followed the instructions to create a clone of my forked git repo (ljhaywar/rtc2git), add the upstream remote (wtfjoke/rtc2git), fetch upstream, checkout origin/master, and merge upstream/master.  At this point, the instructions fall off, and I'm not sure what to do since the code is already committed in the repository.

https://help.github.com/articles/using-pull-requests/ says to create a Pull Request in the GitHub ui, but then all of my changes--not just the commits related to this issue--are being included as part of the pull request.  I'm not sure how to just pull those commits over.

Is there a way for you to merge those two commits into your repo?

**Comment by WtfJoke** [comment]
> I tried this morning, and I'm struggling. I followed the instructions to create a clone of my forked git repo (ljhaywar/rtc2git), add the upstream remote (wtfjoke/rtc2git), fetch upstream, checkout origin/master, and merge upstream/master.

I think after you did that, you should have all commits from my master and could push them to your master. Afterwards you would have needed to do something similar with the develop branch.

Probably something like this:
1. git checkout -b develop_joke upstream/newbranch
2. git push origin develop_joke (with that you have my develop branch in your fork)
3. git checkout -b aPullRequestForJoke (with that you create a new branch based on my develop)
4. .... apply fix somehow
5. git push aPullRequestForJoke
6. use github webinterface for creating the pull request (by selecting branch in list and create pr)

But its ok, I'll try to  merge your commits by hand or will figure something out.  :smile:

**Comment by ljhaywar** [comment]
The sticking point I'm hitting is that the commits are already pushed, so, if I create a new branch, they changes will already be in there.  Thanks for handling the merge!

**Comment by WtfJoke** [comment]
> 1. git checkout -b develop_joke upstream/newbranch

That was slightry wrong.

> I'm hitting is that the commits are already pushed, so, if I create a new branch, they changes will already be in there

The key is to checkout the existing upstream branch. Try the following:
1. git fetch upstream (then it should display something like new branch...)
2. git checkout -b develop_joke upstream/**develop** (then there should be displaying something liike Your branch is up-to-date with upstream/develop)

If there is still something not correct I would try one of the following commands (one after another):
git checkout **.**
git clean -fd
git reset --hard

I really think like that your commits shouldnt be there/already pushed
I hope you dont mind me beeing so persistent on that topic ^^ I just would like that it works out for you :yum:. I think it will be useful in future anyways :relaxed:
