### ISSUE TITLE
Ignore binary files

### ISSUE THREAD

**Issue by ohumbel** [rtcTo/rtc2git#33]
To prevent repository bloat, migrators want to ignore binary files (if so configured).
The configuration should at least list some file types to ignore, such as .zip or .jar.

Some background ...

These are reasons why to avoid big repositories:
http://blogs.atlassian.com/2014/09/ci-git-repos/

These are tips how to handle big files (if not otherwise possible)
http://blogs.atlassian.com/2014/05/handle-big-repositories-git/

**Comment by ohumbel** [comment]
I started to implement a prototype

**Comment by WtfJoke** [comment]
Thanks! Sounds good :+1:  :balloon:

**Comment by ohumbel** [comment]
Just pushed my work in progress as branch 'bigfiles' to my fork (https://github.com/ohumbel/rtc2git).
No live tests passed so far.

**Comment by WtfJoke** [comment]
I think its probably useful to replace the code https://github.com/rtcTo/rtc2git/blob/develop/gitFunctions.py#L65 with an extended version of splitoutputofgitstatusz (where modifier is part of the return value - I guess a simple object will do this job)

**Comment by ohumbel** [comment]
Live tests passed on branch 'bigfiles'.

**Comment by WtfJoke** [comment]
Good. Ready for merge? :+1:

**Comment by ohumbel** [comment]
Yes, soon ready to merge. I am just working on unit tests, and then ...

**Comment by ohumbel** [comment]
Unified parsing of the output of 'git status -z' is implemented with https://github.com/ohumbel/rtc2git/commit/f9fcbc778dcedd95833c066a3b0ba1c7c7ec4d07

**Comment by ohumbel** [comment]
Pull request: https://github.com/rtcTo/rtc2git/pull/45

**Comment by WtfJoke** [comment]
Pull request was merged with 5810698910618dd408e2647593bcd20733928cdc
