### ISSUE TITLE
Running migration a 2nd time on an already migrated repository starts from scratch

### ISSUE THREAD

**Issue by WtfJoke** [rtcTo/rtc2git#44]
The **situation** was as follows:
1. Complete migration of a stream worked flawlessly
2. Couple days later, we wanted to keep up with the stream changes and ran the migration again
3. For some reason, the migration didnt continue and started from 0/the beginning instead

**Analysis**
We figured out, that the workspace was reset to the oldest state.

**Cause**
The reason was that the only baseline on this stream didnt contain anything (Initial Baseline).
This means, setting the components to the baseline durnig the migration will reset the whole workspace, therefore resetting the migrated workspace.

The 2nd run of the migration triggered a reset of the components to the baseline.

**Solution**
Luckily we can detect this situation. If the part until the baseline creation is already migrated, we dont have any changesets to get accepted.

Therefore if we have 0 changesets to accept until the branchpoint, we just dont do anything there and continue with the comparing from the workspace with the stream

@romixch : You can link your commit/fix to this issue
@romixch @ohumbel : I created this issue for documentation purpose

**Comment by ohumbel** [comment]
this was fixed with https://github.com/rtcTo/rtc2git/commit/0a750ff2cd87025fb89cf229f21e19901ecbf384

**Comment by WtfJoke** [comment]
I think the solution has a small flaw. When you have problems while accepting the changes of the stream (https://github.com/rtcTo/rtc2git/blob/develop/migration.py#L76) and then restart it, it will skip those changes.

**Comment by ohumbel** [comment]
The flaw should be fixed with https://github.com/rtcTo/rtc2git/commit/b568a246f5b4f153a2bcad10043e7b7d0797c74a
