### ISSUE TITLE
Link commits with Issue-System (Jira/Github/BitBucket)

### ISSUE THREAD

**Issue by WtfJoke** [rtcTo/rtc2git#48]
If we migrate a RTC project with WorkItems and source code with rtc2jira and rtc2git we would like to maintain existing connections between commits and WorkItems.

In RTC it was possible to assign workitems to changesets and these connection we should keep. 

If we have a commit-message on git with a certain pattern (NUMBER: WorkitemDescription), we can add a prefix so that the commits targets the new system. 

Due the fact that [we keep the same numbers on both systems](https://github.com/rtcTo/rtc2jira/issues/18), a prefix is sufficient and there isnt any need for having a conversion table (oldnumber to newnumber).

**Comment by ohumbel** [comment]
Today I did a live test - works as expected, thanks :+1:

**Comment by WtfJoke** [comment]
Awesome! :tada:  Thanks for testing :smile:
