### ISSUE TITLE
Ability to use -i when loading a workspace

### ISSUE THREAD

**Issue by jacobilsoe** [rtcTo/rtc2git#50]
I have a workspace with multiple components having the same root directory names. So to avoid conflicts I need to specify -i when loading the workspace. 

I propose this be made configurable (or maybe just always use -i when loading).

**Comment by ohumbel** [comment]
I'm in favour of making this configurable. 
Always using `-i` when loading would break existing migrations.

**Comment by WtfJoke** [comment]
Currently I dont have a working copy of lscm/scm. 
What does -i doing?

**Comment by ohumbel** [comment]
It introduces top level directories named after each component. Existing project folders move one level down. Backwards incompatible if hardwired, IMHO

**Comment by jacobilsoe** [comment]
Yes, I agree. It cannot be hardcoded. But it would be very useful to be able to configure it.

**Comment by WtfJoke** [comment]
@jacobilsoe ohumbel was so kind and implemented it. :tada: 
You can test it and tell us if everything is fine like that. Thanks for reporting! :smile:

**Comment by jacobilsoe** [comment]
Thanks, was just about to fix it myself. :-) I will try it out soon.
