### ISSUE TITLE
Streams with spaces in their name lead to all sorts of problems

### ISSUE THREAD

**Issue by ohumbel** [rtcTo/rtc2git#51]
While the `lscm`/`scm` commands are properly quoted, the following problems still exist:
- history files are not found
- git branches get an invalid name

```
History file not found: ~/rtc2git/History/History_BT_Spider_'Cross main stream'.txt

Executed Command: "git show-ref --verify --quiet refs/heads/'Cross main stream'"
fatal: 'Cross main stream' is not a valid branch name.

Executed Command: "git push origin 'Cross main stream'_branchpoint"
fatal: 'Cross main stream_branchpoint' is not a valid branch name.
fatal: remote part of refspec is not a valid name in Cross main stream_branchpoint
```

**Comment by ohumbel** [comment]
Obviously, git branches must not contain spaces.
On the other hand, the tool relies on 
    `streamname == branchname`
in many places.
To really solve this problem, we would need to carry a 
    `streamname -> branchname` conversion table
all around.

A quick fix would be to stop the migration in this case, and inform the user to rename the stream in RTC.

**Comment by WtfJoke** [comment]
It got closed automatically with the merge of the pr. Do we want to investigate further or should I leave it closed?

**Comment by ohumbel** [comment]
I suggest we leave it closed and investigate further as soon as someone really has a problem with it.
