### ISSUE TITLE
Collecting change sets to accept together should be from the same component

### ISSUE THREAD

**Issue by jacobilsoe** [rtcTo/rtc2git#52]
When collecting change sets to accept together in case of merge conflicts, only change sets from the same component should be accepted together.

**Comment by WtfJoke** [comment]
Yup, that would make sense to have that as an additional criteria.
What I wonder is, how do you know from which component the changeset is?

**Comment by jacobilsoe** [comment]
I guess it could be deduced from the history files - in those cases where they are supplied.

**Comment by WtfJoke** [comment]
No, because they history files only contain the uuids. I think to extend them just for this issue would be a little bit too much in my opinion. Maybe there is another way to determine the component of a changeset.

**Comment by jacobilsoe** [comment]
I was thinking of using the **name** of the history file since this name is made up of the stream name and component name.

**Comment by WtfJoke** [comment]
Ah :sweat_smile: Yeah I guess that would be possible'^^

**Comment by ohumbel** [comment]
I already started looking into this...

**Comment by ohumbel** [comment]
You can track what I am doing in this branch: https://github.com/ohumbel/rtc2git/tree/conflictresolution

**Comment by ohumbel** [comment]
Now after all this merging, I should be able to concentrate on this issue again.
However, I am in a different project for the next 2 days.

**Comment by jacobilsoe** [comment]
Let me know if I can help with anything.

**Comment by ohumbel** [comment]
Uh oh an Xcode update on my mac unset my --local user.name and user.email.
But my .ssh key of course is still valid.
Please apologise for 2 commits with 'anyAuthor'.
I think it is not worth rewriting the whole history because of that (see https://help.github.com/articles/changing-author-info/)

**Comment by ohumbel** [comment]
@jacobilsoe I would be very glad if you could verify your use case(s) with my 'conflictresolution' branch (https://github.com/ohumbel/rtc2git/tree/conflictresolution). I am pretty confident that it will work, but have no live data (yet) to test it myself.
If you are satisfied with the result, we can create a pull request and merge it into develop.

**Comment by WtfJoke** [comment]
> Please apologise for 2 commits with 'anyAuthor'.
> I think it is not worth rewriting the whole history because of that (see https://help.github.com/articles/changing-author-info/)

No problem^^ Happens fast.

**Comment by jacobilsoe** [comment]
@ohumbel I tried out your fix in the 'conflictresolution' branch. It works just as it should. Thanks! I also looked through the code and it looks good. So I think you can create a pull request.

**Comment by ohumbel** [comment]
@jacobilsoe A thousand thanks for verifying :flushed:

**Comment by ohumbel** [comment]
The pull request triggers a travis-ci build :fireworks: 
But the usage of enum is only supported from python 3.4 on (see https://docs.python.org/3/library/enum.html). Therefore the python 3.3 build fails. I did not know that, and enum came in handy.

There are 2 ways to fix that:
 - disable the 3.3 build
 - do not use enum

@WtfJoke Manuel what do you propose?

IMHO it is acceptable to require a quite recent version of python.
