### ISSUE TITLE
Migration fails on Windows when using long paths

### ISSUE THREAD

**Issue by jacobilsoe** [rtcTo/rtc2git#61]
Migration on Windows will fail if you have too long paths. The problem is in handle_captitalization_filename_changes where an os.chdir is executed. This will fail if the path is too long:

FileNotFoundError: [WinError 206] The filename or extension is too long

Instead of doing an os.chdir maybe call git ls-files with the folder as argument. Git can be configured to work with long paths like this: `git config --system core.longpaths true` (this works for me at least).

**Comment by WtfJoke** [comment]
How long was the path? Can windows still do stuff there? I mean can you edit the name of the folder for example through the window explorer or can you cd into it in the console (cmd)?

How did core.longpaths changed the behaviour? Afterwards everything worked well with the existing code? If yes, a fix would be easy. We could just set this property in the beginning.

**Comment by jacobilsoe** [comment]
Yes, we should not enable it by default. Maybe write a note about it on the wiki? Enabling it solved my problems though. If I get some time, I will have a look at handle_captitalization_filename_changes.

**Comment by WtfJoke** [comment]
True, a wiki entry would be helpful in that case.

**Comment by WtfJoke** [comment]
I wrote a short [wiki-entry](https://github.com/rtcTo/rtc2git/wiki/Handling-long-paths-%5BWindows%5D). 
You can review it and if necessary enhance/edit it.
