### ISSUE TITLE
Mirror Snapshots in RTC to Tags in GIT

### ISSUE THREAD

**Issue by atruelsen** [rtcTo/rtc2git#63]
It would be really valuable if snapshots in RTC was represented by tags in the corresponding GIT history.
You'd need to read the list of snapshots of the stream since the workspace doesn't show them, but it should be possible to match the baselines of the components to the snapshots from the stream.

**Comment by WtfJoke** [comment]
Thanks for your input!

I personally think thats a great idea for an enhancement. :+1: 
What I dont understand completly is, how you match the baselines of the components to the snapshots of the stream? How are they connected? (I havent used snapshots in rtc, thats why I dont know how they are created/used/or related to other stuff)

**Comment by atruelsen** [comment]
Snapshots are collections of baselines for the components in a stream or workspace.
When creating a snapshot RTC will reuse existing baselines if a component is unchanged or create new ones to capture the current state of each component.
Snapshots are associated with a stream or workspace which means that the snapshots of a stream (Release 1.0/2.0 etc.) cannot be seen on the workspaces flowing to/from the stream, but must be read from the stream.

**Comment by WtfJoke** [comment]
Ah I think I saw some of them.... Sometimes they get even created automatically, right? (for example by builds or when youre out of sync and replace your workspace)

Currently I have no acess to a rtc stream which has snapshots (I left the company where we used rtc and therefore dont have access anymore to this data).
I might be able to create/extend a teststream on hub.jazz.net. 

Or do you want to implement that feature?

**Comment by WtfJoke** [comment]
Anders, I just wanted to let you know, that our other project [rtc2gitcli ](https://github.com/rtcTo/rtc2gitcli) supports the migration of snapshots. :smile: 

Give it a try and let us know if you encounter any problems.

Therefore I'll close this issue here.

**Comment by himmakam** [comment]
@WtfJoke , you were mentioning that our other project rtc2gitcli supports the migration of snapshots.

I see the baselines inclusion property in migration.properties. Do we need to set any thing for migration of snapshots. OR it automatically does. Please do let me know. Thanks
