### ISSUE TITLE
.jazzignore -> .gitignore

### ISSUE THREAD

**Issue by ohumbel** [rtcTo/rtc2git#66]
At the moment you have to convert your .jazzignore files by hand.
The tool prompts you to do so at the end of the migration.

The first step would be to do this automatically.
And the final version should also track those files during the migration.

My branch `jazzignore` is intended to hold the implementation

**Comment by WtfJoke** [comment]
You want to give it a second try? :smiley: 
It would be really awesome if you can manage to convert them automatically. :raised_hands:





> And the final version should also track those files during the migration.

Do you mean with that, the .jazzIgnore files which are created/modified during the time?



If you need any help, let me know.

**Comment by ohumbel** [comment]
Yes.
As a tool who claims to preserve history, we should also follow the lifecycle of the different .jazzignore files. At least it would be nice if we could.

I'll give it another try because my first production migration already has > 12 ignore files. And the translation should be pretty straightforward.

**Comment by ohumbel** [comment]
A basic translation of a .jazzignore file is working.
[Please expect me to be less responsive during the next two weeks - I am on holidays with my family.]

**Comment by WtfJoke** [comment]
Cool, sounds great.

No problem, enjoy your holidays. :sunny: :palm_tree:
