### ISSUE TITLE
Check ignored files which still are present

### ISSUE THREAD

**Issue by ohumbel** [rtcTo/rtc2git#72]
At the end of the migration, I want to list all files still present in the tip of the workspace having one of the excluded extensions.

These files are either excluded by mistake, or need to be processed further.

Examples use cases: 
 - an `.ico` file which should not have been excluded
 - a `.jar` file which should be retrieved from maven central or artifactory

**Comment by WtfJoke** [comment]
Why is that necessary? I mean dont we need to list all files with excluded extensions somwhere in the workspace if we do something like that you describe and not just the tip?

Or is the aim to help the user to decide if that what he excluded was really that what he wanted to and didnt exclude something by accident?

**Comment by ohumbel** [comment]
No problem, you are right.

I try to explain what I meant...
Every single file that was excluded during the whole migration is listed in `.gitignore`. This list can grow very large.

I am not interested in the history of binary files like .zip or .jar. But I am interested if the tip still contains such "excluded" files (since the exclusion by extension is really global). If this is the case, I need to take some action. Either I have to adjust the ignored extensions, or I need another solution for the files still present.

What I want to implement is a cross check between `.gitignore` and the tip. This would be very tedious to do by hand and helps a lot, even for our simplest migrations. For example I am able to detect that `*.ico` and `*.svg` files really are needed for Web projects. This led to an adjustment of the ignored extensions. On the other hand, there were some external `.jar` files still lingering around. My colleagues now removed them completely.

I admit that this maybe is a very special case, but the implementation is straightforward and has absolutely no side effects (see https://github.com/ohumbel/rtc2git/commit/2a6ebb47b90f0b48b9868f117428506c04080367)

**Comment by ohumbel** [comment]
This is an example output from a live migration today:

```
All changes accepted - Migration of stream 'EnterpriseMgmtServices_Stream' is completed.
You can distribute the git-repo 'EMS.git'.
16:59:34 - 
The following files have been ignored in the new git repository, but still exist in the actual RTC workspace:
16:59:34 - 	
16:59:34 - 	/EmsConsole/WebContent/node_modules
16:59:34 - 	EmsPersistence/test_db/ems.h2.db
16:59:34 - 	EmsPersistence/test_db/ems.trace.db
```

After talking to the developers, `node_modules` are OK to be excluded completely, but the `*.db` files are still under investigation. The good news is: all the rest is fine :+1:

**Comment by WtfJoke** [comment]
Ok got it now. Thanks for the detailed explaination

**Comment by ohumbel** [comment]
Travis is green - best wishes from Devoxx

**Comment by WtfJoke** [comment]
Awesome! Enjoy Devoxx:smile:
