### ISSUE TITLE
Enable line ending normalization for text files

### ISSUE THREAD

**Issue by ohumbel** [rtcTo/rtc2git#73]
For multi platform projects, line endings in text files (`CR` vs. `CRLF`) are always an issue.
A `.gitattributes` file helps handling these line endings on a per repository basis.

I want to create a minimal `.gitattributes` file, if so specified in `config.ini`.

Further reading:
https://help.github.com/articles/dealing-with-line-endings/
http://stackoverflow.com/questions/170961/whats-the-best-crlf-carriage-return-line-feed-handling-strategy-with-git

**Comment by WtfJoke** [comment]
Makes sense^^ Since we rum into similar issues with even this small repository :smile:
