### ISSUE TITLE
output of git status -z should not be stripped

### ISSUE THREAD

**Issue by ohumbel** [rtcTo/rtc2git#75]
Since the whole purpose of `git status -z` is to have a formatted output, it is *wrong* to strip these lines.
Currently we miss deletions of `.jazzignore`, because the deletion mark starts at position 2 (blanks indicated as `_` below):

`_D_theFolder/.jazzignore`

**Comment by WtfJoke** [comment]
Do you mean this stripping here [shell.py#L19](https://github.com/rtcTo/rtc2git/blob/develop/shell.py#L19)?

And to the issue itself: Ouch, that hurts :frowning:

**Comment by ohumbel** [comment]
Yes, exactly that stripping (plus an additional one in the parsing of git status -z).
It did not yet hurt too much. I stumbled over it while trying to fix the many "invalid date" errors seen in the  travis log. 
And I thought of an additional parameter as well. I do not know which logic is depending on the stripping. Maybe only of the exclusion of blank lines?

**Comment by ohumbel** [comment]
@WtfJoke any chance to have a look at my pull request?

**Comment by WtfJoke** [comment]
Yup, sorry. Somehow overlooked it. Thanks for fixing :)
