### ISSUE TITLE
Travis build sometimes failing

### ISSUE THREAD

**Issue by ohumbel** [rtcTo/rtc2git#77]
It is now at least the second time that a travis build fails, but there were no logical changes.
Last time: just after @WtfJoke accepted my pull request.
The time before: just after creation of my pull request.

I suggest we have an eye on the concrete tests failing in these cases. I suspect there are only a few "flaky" ones.

**Comment by ohumbel** [comment]
So here is the first candidate, which failed the last two times:
```
======================================================================
FAIL: test_BranchRenaming_TwoCallsAtTheSameTime_ShouldFail (test_gitFunctions.GitFunctionsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/rtcTo/rtc2git/tests/test_gitFunctions.py", line 105, in test_BranchRenaming_TwoCallsAtTheSameTime_ShouldFail
    self.assertEqual(1, Commiter.promotebranchtomaster(branchname))
AssertionError: 1 != 0
```

**Comment by WtfJoke** [comment]
Yeah I noticed that outside of travis as well. Its kinda a race condition which fails. It fails as soon the two successive calls arent called in the same second.

**Comment by ohumbel** [comment]
Cool - did not know that it was that way time sensitive.
Thanks!
