### ISSUE TITLE
Release Version 1.2

### ISSUE THREAD

**Issue by WtfJoke** [rtcTo/rtc2git#80]
We should create a new release soon.

There were a lot of enhancements/fixes since the latest release (1.1) happend in june.

**Comment by ohumbel** [comment]
I totally agree that it is time for a new release!

Personally I'd like to round up the whole ignore / exclusion theme. It would be nice if #74 and #81 could be done first. I soon have a solution ready for #74, and #81 should be very easy.

But of course, there is always one more issue to fix :wink:

**Comment by WtfJoke** [comment]
Version 2.0 is already released
