### ISSUE TITLE
Getting Component History Programmatically

### ISSUE THREAD

**Issue by PernusBernus** [rtcTo/rtc2git#84]
Hi, having played around with rtc2git (excellent piece of work btw :+1:) a bit, I wrote a little bash script to make getting the history files less arduous. Setting the maximum number of results for `scm list changesets` to 1M seems to work perfectly for my migration scenario (2K+ changesets in each component). I'll just leave [this](https://github.com/PernusBernus/getRTCHistory) here...

**Comment by WtfJoke** [comment]
Hi Thomas, thanks for your feedback, Im happy to hear that :)

First of, thank you very much for your script. :+1: 

However currently im not sure, wheter scm list changesets did the job right in terms of ordering. We had some problems finding the right order of the changesets in the past.

I am going to crawl through some old comments and/or code to check if I can figure out if the ordering is correct or not.

But if it worked out for you perfectly im more than happy. :)
Probably I will link it  anyways in the wiki (https://github.com/rtcTo/rtc2git/wiki/Getting-your-History-Files) as an alternative approach if you agree of course :smile:

**Comment by PernusBernus** [comment]
Ah ok, didn't know about scm's ordering issue, haven't really looked into that at all. Though feel free to link my script if you think it'd be useful. Keep up the good work! :clap:

**Comment by ohumbel** [comment]
@PernusBernus thanks a lot for the flowers - we like them a lot :wink:

**Comment by WtfJoke** [comment]
In the meantime (yeah took a little bit too long), I updated the [wiki ](https://github.com/rtcTo/rtc2git/wiki/Getting-your-History-Files#still-want-to-try-to-do-it-automatically) with your repository. Thanks again for sharing :smiley:
