### ISSUE TITLE
.gitignore files get lost

### ISSUE THREAD

**Issue by ohumbel** [rtcTo/rtc2git#85]
Today I had the shock of my life...

Well not really, but quite a shock: A colleague told me that the migrated git repository misses `.gitignore` files.

Debugging the whole migration showed that we follow the lifecycle of `.jazzignore`/`.gitignore` absolutely perfect. But nonetheless, at the end of the migration all `.gitignore` files were absent.

Debugging twice again - and focussing on the removal of `.gitignore` files - showed this in the console:

```
11:14:48 - Accepting: 22404: Enterprise LOGIN: Create enterprise repository - created ant/build xml (Date: 2013-11-14 13:33:14, Author: Tanner Markus, Revision: _0ksH0k0oEeOFO7Ms2bLlhg, Component: _81p5sDJnEeOq9PDTyN2FkQ, Accepted: False)
11:14:48 - Executed Command: "lscm accept -v -o -r https://rtc.bison-group.com/ccm/ -t HUO_Migrate_EMS3 --changes _0ksH0k0oEeOFO7Ms2bLlhg" --> /home/huo/gitrepos/ohumbel/rtc2git/Logs/accept.txt
11:14:48 - Executed Command: "git diff --quiet"
11:14:48 - Start (re)loading current workspace: lscm load -r https://rtc.bison-group.com/ccm/ HUO_Migrate_EMS3 --force
11:14:48 - Executed Command: "lscm load -r https://rtc.bison-group.com/ccm/ HUO_Migrate_EMS3 --force"
The following resources had uncommitted changes and were overwritten:
  A copy of each file is available in "/d500/rtcmigrated/migrate_EMS3/EMS3/.jazzShed/b15-11-30_11.14.49.595".
    /EnterpriseConsole/.gitignore
    /EnterpriseMgmtService/.gitignore
    /EmsPersistence/.gitignore
Successfully loaded items into the sandbox.
11:14:49 - Load of workspace finished
11:14:49 - Accepted change 11/498 into working directory
11:14:49 - Executed Command: "git status --untracked-files=all -z"
```

**Comment by ohumbel** [comment]
A quick first analysis: We have to `reload --force` the RTC workspace, because an accept not always arrives in the local filesystem (these cases are detected by `git diff --quiet`). Such a reload seems to copy the `.gitignore` files into `.jazzShed/`.

**Comment by WtfJoke** [comment]
Yeah I know. I have seen that by the logfile you provided. 
A simple solution would be to create the gitignore file later, after the loading of the workspace. Cause once its commited, it wont get lost anymore.

**Comment by ohumbel** [comment]
Exactly.
Because `.gitignore` is not known to RTC, it will always be removed on `force reload`, regardless of the git status. In my case everything was already committed to git...

My strategy is to:
 - catch the output of the `force` command
 - detect if something was copied to `.jazzShed`
 - if yes, copy all the `.gitignore` files back from there

**Comment by ohumbel** [comment]
Or - better - check them out from git again.
This is probably the safer way.

**Comment by ohumbel** [comment]
Thanks @reinhapa for bringing me back to the safe path!

The implementation will be as follows:
 - detect a `reload --force`
 - scan all deletions (from the output of `git status -z`)
 - for all `.gitignore` files that were deleted and have a sibling `.jazzignore` file: `git checkout -- gitignorefilename`
 - update `git status -z` if necessary

**Comment by ohumbel** [comment]
This was a hard nut to crack.
Pull request #86 fixes it.

**Comment by WtfJoke** [comment]
> Or - better - check them out from git again.
> This is probably the safer way

Great Idea! Didnt think about that. Nice one! :+1: :ok_hand:

**Comment by ohumbel** [comment]
PR #86 is now updated with new tests. 
The sibling check was missing. This could lead to very strange errors.
Now I am confident that this issue is really solved :wink:
