### ISSUE TITLE
How can I tell rtc2git not to migrate specific files in my RTC repository ?

### ISSUE THREAD

**Issue by keithvb1** [rtcTo/rtc2git#99]
I used rtc2git to migrate successfully a small , relatively small rtc repository to git. This had no binary files. I attempted to migrate a large rtc repository of app 2500 src files where app 130 files are binary. It failed after running 13hrs at 90% complete. It seems to have failed trying to resolve conflict for binary file.
Is there a way I can tell rtc2git to ignore certain files ? I appreciate the help !   failure log attached. 
[rtc2git.failure.txt](https://github.com/rtcTo/rtc2git/files/194162/rtc2git.failure.txt)

**Comment by WtfJoke** [comment]
I think at the moment its not possible to do that using the script.
What probably is possible that you can start the migration, pause (by aborting it) and edit the .gitignore file and add your file there. 

So git wont track it. But when I get your problem right, its more a problem with your rtc workspace, than rather with the git part. Am I right?

You could also try and check out [rtc2gitcli](https://github.com/rtcTo/rtc2gitcli). There, the conflict part should happen less likely or not at all

**Comment by keithvb1** [comment]
Thank you WtfJoke for the response. I assume if I could tell the tool not to look at my binary files, then all would be well. I understand about the .gitinore and the .jazzignore files. I will look into that .
Cheers

**Comment by WtfJoke** [comment]
Reopen the issue if you got some questions left. :)

**Comment by AdamBrousseau** [comment]
Somewhat related: You can also use git filter-branch to remove files from history after the migration. I was able to do so using these instructions: http://dalibornasevic.com/posts/2-permanently-remove-files-and-folders-from-git-repo
